# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transaction.proto',
  package='blackhole',
  syntax='proto3',
  serialized_pb=_b('\n\x11transaction.proto\x12\tblackhole\"^\n\x0b\x42\x61nkRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12 \n\x04type\x18\x03 \x01(\x0e\x32\x12.blackhole.TxnType\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x02\"0\n\tBankReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nnewBalance\x18\x02 \x01(\x02*&\n\x07TxnType\x12\x0b\n\x07\x44\x45POSIT\x10\x00\x12\x0e\n\nWITHDRAWAL\x10\x01\x32\x41\n\x04\x42\x61nk\x12\x39\n\x07\x44\x65posit\x12\x16.blackhole.BankRequest\x1a\x14.blackhole.BankReply\"\x00\x42;\n\'com.clarabridge.examples.grpc.blackholeB\x0e\x42lackholeProtoP\x01\x62\x06proto3')
)

_TXNTYPE = _descriptor.EnumDescriptor(
  name='TxnType',
  full_name='blackhole.TxnType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEPOSIT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WITHDRAWAL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=178,
  serialized_end=216,
)
_sym_db.RegisterEnumDescriptor(_TXNTYPE)

TxnType = enum_type_wrapper.EnumTypeWrapper(_TXNTYPE)
DEPOSIT = 0
WITHDRAWAL = 1



_BANKREQUEST = _descriptor.Descriptor(
  name='BankRequest',
  full_name='blackhole.BankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='blackhole.BankRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account', full_name='blackhole.BankRequest.account', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='blackhole.BankRequest.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='blackhole.BankRequest.amount', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=126,
)


_BANKREPLY = _descriptor.Descriptor(
  name='BankReply',
  full_name='blackhole.BankReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='blackhole.BankReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newBalance', full_name='blackhole.BankReply.newBalance', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=176,
)

_BANKREQUEST.fields_by_name['type'].enum_type = _TXNTYPE
DESCRIPTOR.message_types_by_name['BankRequest'] = _BANKREQUEST
DESCRIPTOR.message_types_by_name['BankReply'] = _BANKREPLY
DESCRIPTOR.enum_types_by_name['TxnType'] = _TXNTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BankRequest = _reflection.GeneratedProtocolMessageType('BankRequest', (_message.Message,), dict(
  DESCRIPTOR = _BANKREQUEST,
  __module__ = 'transaction_pb2'
  # @@protoc_insertion_point(class_scope:blackhole.BankRequest)
  ))
_sym_db.RegisterMessage(BankRequest)

BankReply = _reflection.GeneratedProtocolMessageType('BankReply', (_message.Message,), dict(
  DESCRIPTOR = _BANKREPLY,
  __module__ = 'transaction_pb2'
  # @@protoc_insertion_point(class_scope:blackhole.BankReply)
  ))
_sym_db.RegisterMessage(BankReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\'com.clarabridge.examples.grpc.blackholeB\016BlackholeProtoP\001'))

_BANK = _descriptor.ServiceDescriptor(
  name='Bank',
  full_name='blackhole.Bank',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=218,
  serialized_end=283,
  methods=[
  _descriptor.MethodDescriptor(
    name='Deposit',
    full_name='blackhole.Bank.Deposit',
    index=0,
    containing_service=None,
    input_type=_BANKREQUEST,
    output_type=_BANKREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANK)

DESCRIPTOR.services_by_name['Bank'] = _BANK

# @@protoc_insertion_point(module_scope)
